

services:

 sqlserver:
  image:
   mcr.microsoft.com/mssql/server
  
  container_name:
   mssqlserver_container    
  
  volumes:
   - sqlserver_volume:/var/opt/mssql
  ports:
   - "1433:1433" 
  networks:
   - application_net
  environment:
   - ACCEPT_EULA=Y


networks:
 application_net:
  driver:
   bridge

volumes:
    sqlserver_volume: