services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres_container    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - application_net
 

  web_api:
    build: .
    container_name:
      webAPI_container
    networks:
      - application_net
    ports:
      - "8081:8080"  
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - application_net
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  application_net:
    driver:
     bridge

volumes:
  postgres-data: